# GitHub Actions workflow to publish the package to NPM when a new release is published
name: Publish to NPM

on:
  # Triggered when a new tag is added
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'
  # Allows manual trigger via "Actions" tab
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Publish the package to NPM
      - name: Publish package
        run: npm publish --provenance
